name: Build CI

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  Build:
    uses: ./.github/workflows/build.yml
    with:
      variant: Debug
    secrets:
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}